controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

# Front Office
app_home: # Page Accueil
  path: /
  controller: App\Controller\HomeController::index

#  Page de la bibliotheque
app_bibliotheque:    # Liste des séries 
  path: /bibliotheque
  controller: App\Controller\BibliothequeController::index

app_detail_serie:  # Liste détaillé des mangas par série
  path: /bibliotheque/{id}
  controller: App\Controller\BibliothequeController::detail


# Back Office Admin
app_admin:
  path: /admin
  controller: App\Controller\Admin\DashboardController::index

app_admin_member_management:
  path: /admin/members
  controller: App\Controller\AdminController::memberManagement

# Back Office Member
app_member:
  path: /member/profile
  controller: App\Controller\MembreController::index

app_member_readList:
  path: member/readList
  controller: App\Controller\MembreController::readList

app_member_createList:
  path: /member/createList
  controller: App\Controller\MembreController::createList
  methods: [GET, POST]

app_member_editList:
  path: /member/editList/{id}
  controller: App\Controller\MembreController::editList
  methods: [GET, POST]

app_member_deleteList:
  path: /member/deleteList/{id}
  controller: App\Controller\MembreController::deleteList
  methods: [GET, POST]

# Login / Logout
app_login:
  path: /login
  controller: App\Controller\SecurityController::login
  methods: [GET, POST]

app_logout:
  path: /logout
  methods: GET

# Inscription
app_register:
  path: /register
  controller: App\Controller\RegistrationController::register

app_verify_email:
  path: /verify/email
  controller: App\Controller\RegistrationController::verifyUserEmail

app_email_conf_sent:
  path: /signup/confirmation
  controller: App\Controller\RegistrationController::postSignUp


# Stripe
app_stripe:
  path: /stripe
  controller: App\Controller\StripeController::index

app_stripe_charge:
  path: /stripe/create-charge
  controller: App\Controller\StripeController::createCharge
  methods: POST

app_stripe_success:
  path: /order/confirmation
  controller: App\Controller\StripeController::orderConfirmation

app_stripe_fail:
  path: /payment/failure
  controller: App\Controller\StripeController::paymentFailure